name: new_bmi_calculator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  lints: ^4.0.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3
  vm_service: ^14.2.5

flutter:
  uses-material-design: true

  assets:
    - images/ima.png
